### ISSUE TITLE
Settle fragment has static list of groups

### ISSUE THREAD

**Issue by ManimalaC** [sda5-walletdroid/walletdroid#55]
Currently settle fragment has a static spinner. code needs to be changed to dynamically build the spinner to have only those groups where the current user is an admin

**Comment by Mehdi-Attarpour** [comment]
I think settle fragment is going to be combined by group fragment. So there won't be a settle fragment anymore.
@ManimalaC

**Comment by ManimalaC** [comment]
the fragment is merged with groups and using group adapter to fetch the data now
